{
 "title": "Gluu",
 "description": "Dashboard that graphs metrics exported via gluu-metrics plugin in Kong(https://github.com/GluuFederation/gluu-gateway)",
 "time": { "from": "now/M", "to": "now/M" },
 "refresh": "1d",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(gluu_endpoint_method,service)"
   },
   {
    "name": "endpoint",
    "query": "label_values(gluu_endpoint_method,endpoint)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Authentication",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gluu_total_client_authenticated[30d]))",
     "legendFormat": "Total Authentication"
    }
   ]
  },
  {
   "title": "Total Authorization Granted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gluu_total_client_granted[30d]))",
     "legendFormat": "Total Granted"
    }
   ]
  },
  {
   "title": "OpenID Connect Authentication",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gluu_openid_connect_users_authenticated{service =~ \"$service\"}[30d]))",
     "legendFormat": "OpenID Connect Authentication"
    }
   ]
  },
  {
   "title": "OAuth Client Authenticated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gluu_oauth_client_authenticated{service =~ \"$service\"}[30d])) by (consumer)",
     "legendFormat": "{{consumer}}"
    }
   ]
  },
  {
   "title": "OAuth Client Granted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gluu_oauth_client_granted{service =~ \"$service\"}[30d])) by (consumer)",
     "legendFormat": "{{consumer}}"
    }
   ]
  },
  {
   "title": "UMA Client Authenticated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gluu_uma_client_authenticated{service =~ \"$service\"}[30d])) by (consumer)",
     "legendFormat": "{{consumer}}"
    }
   ]
  },
  {
   "title": "UMA Client Granted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gluu_uma_client_granted{service =~ \"$service\"}[30d])) by (consumer)",
     "legendFormat": "{{consumer}}"
    }
   ]
  },
  {
   "title": "Permission Ticket issued",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gluu_uma_ticket{service =~ \"$service\"}[30d]))",
     "legendFormat": "Ticket"
    }
   ]
  },
  {
   "title": "Total requests per methods per service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gluu_endpoint_method{service =~ \"$service\", endpoint =~ \"$endpoint\"}[30d])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}