<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_aaap</name>
   <tag></tag>
   <elementGuidId>40f192f8-e898-4264-b18c-e090c0643741</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clickable ng-binding</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-sref</name>
      <type>Main</type>
      <value>apis.edit({api_id:api.id})</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#!/apis/8d87bfcb-ddb0-4f1e-b428-c43d2ed35652/edit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>aaap</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;konga&quot;)/body[@class=&quot;body ng-scope _expose-aside&quot;]/div[@class=&quot;main-container-wrapper side-nav--animatable&quot;]/div[@class=&quot;main-container-wrapper-static&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;main-container container&quot;]/div[@class=&quot;main-container-inner ng-scope&quot;]/div[@class=&quot;row ng-scope&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-hover table-striped&quot;]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[3]/strong[1]/a[@class=&quot;clickable ng-binding&quot;]</value>
   </webElementProperties>
</WebElementEntity>
