# coding: utf-8

"""
    Simple Inventory API

    This is a simple API

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.developers_api import DevelopersApi


class TestDevelopersApi(unittest.TestCase):
    """ DevelopersApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.developers_api.DevelopersApi()

    def tearDown(self):
        pass

    def test_search_inventory(self):
        """
        Test case for search_inventory

        searches inventory
        """
        pass


if __name__ == '__main__':
    unittest.main()
