{
 "title": "Gluu Gateway",
 "description": "Dashboard that graphs metrics exported via gluu-metrics plugin in Kong(https://github.com/GluuFederation/gluu-gateway)",
 "time": { "from": "now/M", "to": "now/M" },
 "templating": {
  "list": [
   {
    "name": "CustomersTarget",
    "query": "label_values(gluu_endpoint_method,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Authentication",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gluu_total_client_authenticated{instance =~ \"$CustomersTarget\"}[30d]))",
     "legendFormat": "Total Authentication"
    }
   ]
  },
  {
   "title": "Total Authorization Granted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gluu_total_client_granted{instance =~ \"$CustomersTarget\"}[30d]))",
     "legendFormat": "Total Authorization Granted"
    }
   ]
  },
  {
   "title": "OpenID Connect Authentication",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gluu_openid_connect_users_authenticated{instance =~ \"$CustomersTarget\"}[30d]))",
     "legendFormat": "OpenID Connect Authentication"
    }
   ]
  },
  {
   "title": "OAuth Client Authenticated",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gluu_oauth_client_authenticated{instance =~ \"$CustomersTarget\"}[30d])) by (consumer)",
     "legendFormat": "{{consumer}}"
    }
   ]
  },
  {
   "title": "OAuth Client Granted",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gluu_oauth_client_granted{instance =~ \"$CustomersTarget\"}[30d])) by (consumer)",
     "legendFormat": "{{consumer}}"
    }
   ]
  },
  {
   "title": "UMA Client Authenticated",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gluu_uma_client_authenticated{instance =~ \"$CustomersTarget\"}[30d])) by (consumer)",
     "legendFormat": "{{consumer}}"
    }
   ]
  },
  {
   "title": "UMA Client Granted",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gluu_uma_client_granted{instance =~ \"$CustomersTarget\"}[30d])) by (consumer)",
     "legendFormat": "{{consumer}}"
    }
   ]
  },
  {
   "title": "OPA PEP Granted",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(gluu_opa_client_granted{instance =~ \"$CustomersTarget\"}[30d])) by (consumer)",
     "legendFormat": "{{consumer}}"
    }
   ]
  }
 ]
}