global:
  scrape_interval: 12h
  evaluation_interval: 12h
alerting:
  alertmanagers:
    - static_configs:
        - targets: null
rule_files: null
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - 'localhost:9090'
  - job_name: gluu_gateway
    metrics_path: /gluu-metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - dev1.gluu.org
          - dev2.gluu.org
          - test2.org
          - test3.org
          - test5.org
          - test6.org
