<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>add_plugin_close</name>
   <tag></tag>
   <elementGuidId>a1114fa8-a9a2-4193-ac4e-173236581fe6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.modal-close</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div[1]/h4/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
