#!/bin/bash
### BEGIN INIT INFO
# Provides:          konga
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

SERVICE_NAME=konga
PID_PATH_NAME=/var/run/konga.pid
TMP_PID_PATH_NAME=/tmp/konga.pid
BASEDIR=/opt/gluu-gateway/konga/
KONGA_INIT_LOG=/var/log/konga.log

get_pid() {
	if [ -f $PID_PATH_NAME ]; then                
		PID_NUM=$(cat $PID_PATH_NAME)
		echo "$PID_NUM"
	else
		OTHER_GATEWAY_PID="`ps -eaf|grep -i node|grep -v grep|grep -i '\-\-harmony app.js'|awk '{print $2}'`"
		###For one more possible bug, find and kill oxd                
		if [ "x$OTHER_GATEWAY_PID" != "x" ]; then
			echo "$OTHER_GATEWAY_PID"
		fi
	fi
}

do_start () {        
	PID_NUM=`get_pid`
        if [ "x$PID_NUM" = "x" ]; then         
                echo "Starting $SERVICE_NAME ..."                

		cd $BASEDIR
                nohup node --harmony app.js --prod >> $KONGA_INIT_LOG 2>&1 &
                echo $! > $TMP_PID_PATH_NAME        
                START_STATUS=`tail -n 12 $KONGA_INIT_LOG|grep -i 'To see your app, visit'`
                ERROR_STATUS=`tail -n 10 $KONGA_INIT_LOG|grep -i 'Error'`
                if [ "x$START_STATUS" = "x" ]; then
			###If by chance log file doesn't provide necessary string, sleep another 10 seconds and check again PID of process
			sleep 5
			PID_NUM=`get_pid`
        		if [ "x$PID_NUM" = "x" ]; then
                        	### Since error occurred, we should remove the PID file at this point itself.                        
                        	echo "Some error encountered..."                        
                        	echo "See log below: "                        
                        	echo ""                        
                        	echo "$ERROR_STATUS"                        
                        	echo ""                        
                        	echo "For details please check $KONGA_INIT_LOG ."                        
                        	echo "Exiting..."                        
                        	exit 255
                	fi

		fi
                mv $TMP_PID_PATH_NAME $PID_PATH_NAME                        
        	PID_NUM=$(cat $PID_PATH_NAME)
        else                
	        if ps aux | grep -v "grep" | grep -w $PID_NUM\ .*.node > /dev/null 2>&1; then
                        echo "$SERVICE_NAME is already running ..."        
	        else
		        kill -9 $PID_NUM > /dev/null 2>&1
			rm -f $PID_PATH_NAME > /dev/null 2>&1
			do_start
			exit
        fi        
        echo "PID: [$PID_NUM]"
}

do_stop () {        
	PID_NUM=`get_pid`
        if [ "x$PID_NUM" != "x" ]; then                
                echo "$SERVICE_NAME stoping ..."            
                kill -9 $PID_NUM > /dev/null 2>&1            
                rm -f $PID_PATH_NAME > /dev/null 2>&1        
        else   
                echo "$SERVICE_NAME is not running ..."        
        fi
}

case $1 in
    start)
            do_start
    ;;
    stop)
            do_stop
    ;;
    restart)
            do_stop
            do_start
    ;;
    status)
        if [ -f $PID_PATH_NAME ]; then
            echo "$SERVICE_NAME is running ...";
            PID_NUM=$(cat $PID_PATH_NAME)                
            echo "PID: [$PID_NUM]"
        else
           echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
        RETVAL=2
    ;;
esac 
