#!/bin/sh
set -e

if [ -f /etc/init.d/gluu-gateway ]; then
    update-rc.d gluu-gateway remove > /dev/null 2>&1
fi
rm -rf /opt/gluu-gateway > /dev/null 2>&1
rm -rf /opt/jdk1.8.0_162 > /dev/null 2>&1
rm -rf /opt/jre > /dev/null 2>&1

if [ "$1" = purge ]; then
    if [ -f /etc/init.d/gluu-gateway ]; then
        rm -rf /etc/init.d/gluu-gateway > /dev/null 2>&1
    fi
    if [ -f /etc/init.d/kong ]; then
        rm -rf /etc/init.d/kong > /dev/null 2>&1
    fi
    if [ -f /etc/init.d/konga ]; then
        rm -rf /etc/init.d/konga > /dev/null 2>&1
    fi  
    if [ -f /lib/systemd/system/gluu-gateway.service ]; then
        rm -rf /lib/systemd/system/gluu-gateway.service > /dev/null 2>&1
	rm -rf /lib/systemd/system/kong.service > /dev/null 2>&1
	rm -rf /lib/systemd/system/konga.service > /dev/null 2>&1
    fi
    service postgresql start
    su postgres -c "psql -c \"DROP DATABASE kong;\"" > /dev/null 2>&1
    su postgres -c "psql -c \"DROP DATABASE konga;\"" > /dev/null 2>&1
fi

# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload > /dev/null 2>&1 || true
fi
