<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_94bf787c-a42d-4a66-b8d3-41d</name>
   <tag></tag>
   <elementGuidId>e34ab56f-2071-4724-b9a7-dc2bf1e9f612</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;konga&quot;]/body/div[1]/div/div/div[2]/table/tbody/tr[3]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>94bf787c-a42d-4a66-b8d3-41d756a8bc7c</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;konga&quot;]/body/div[1]/div/div/div[2]/table/tbody/tr[3]/td[2]</value>
   </webElementProperties>
</WebElementEntity>
