name: Gluu Gateway CI

on:
  push:
    paths:
      - 'kong/**'
      - 't/lib/**'
      - 't/specs/**'
      - 't/Dockerfile'
      - 't/run.sh'
      - 't/run-flow.sh'

jobs:

  build:
 
    runs-on: ubuntu-16.04
 
    steps:
    - name: Fix up git URLs
      run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Run Test cases
      run: ./t/run.sh
